# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'
    - name: Build with Maven
      run: mvn -Pproduction --batch-mode --update-snapshots verify
    - run: cp docker-compose.yml ./target  
    - name: Archive artifacts
      uses: actions/upload-artifact@v1
      with: 
        name: app
        path: ./target/
    
    
  deploy:
    runs-on: ubuntu-latest
    needs: [build, ]
    steps:
    - name: Download app artifacts
      uses: actions/download-artifact@v1
      with:
        name: app
    - name: Copy host via scp
      uses: appleboy/scp-action@v0.1.3
      with:
        HOST: ${{ secrets.SSH_HOST }}
        USERNAME: ${{ secrets.SSH_USER }}
        PORT: 22
        KEY: ${{ secrets.SSH_PRIVATE_KEY }}  
        source: "app/*"
        target: "/home/${{ secrets.SSH_USER }}/"
        strip_components: 1
        rm: false
        overwrite: true

# see https://github.com/appleboy/scp-action/issues/52
    - name: Executing remote command
      uses: appleboy/ssh-action@v0.1.3
      with:
        HOST: ${{ secrets.SSH_HOST }}
        USERNAME: ${{ secrets.SSH_USER }}
        PORT: 22
        KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd /home/${{ secrets.SSH_USER }}/
          mkdir ./letsencrypt
          touch ./letsencrypt/acme.json
          sudo chmod 0600 ./letsencrypt/acme.json
          sudo docker-compose down --remove-orphans
          sudo echo "PUB_IP=${{ secrets.SSH_HOST }}" | sed -e 's/\./-/g' > .env
          sudo docker-compose up -d
          
